<section>
    <h1><?= $judul ?></h1>
    <p align="justify">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Labore quibusdam harum voluptatibus est quaerat dolorem obcaecati voluptatum quae exercitationem voluptate, delectus nemo, voluptatem optio sit dignissimos nobis dolorum, corporis ad aut accusamus modi provident. Nulla laboriosam sint nemo. Perferendis ea aut inventore laboriosam quidem ipsa minus architecto ipsam vitae soluta.</p>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa eos vitae maxime optio maiores, dicta ea neque necessitatibus voluptatum quo?</p>

    <ol type="a">
    <li>Model</li>
    <p align="justify">Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam magni optio dolorem eum autem libero expedita eveniet explicabo. Ea expedita dignissimos animi ratione totam deserunt sed, pariatur velit odit aliquam ut asperiores incidunt nam recusandae similique, molestias nihil aperiam id, atque molestiae eaque. Qui nesciunt aperiam asperiores eius nihil ipsam quos dolorum porro, cum tenetur ipsum officiis non velit odio temporibus. Laudantium nobis quas nesciunt dolor! Laborum odit aliquid optio.</p>
    <p align="justify">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea odio cumque cum consequuntur, ipsum fugiat.</p>
    <p align="justify">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae rem maxime voluptate neque? Cum delectus voluptatem placeat veritatis quas perspiciatis consectetur impedit omnis aut tempore, adipisci, amet laboriosam eligendi ratione atque! Qui similique ipsum cupiditate?</p>
    <p align="justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat incidunt ab facilis cum dolor illum magnam perspiciatis asperiores quibusdam eaque vero assumenda, nihil, suscipit eos quos, deserunt porro expedita aliquid?</p>
    <p align="justify">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestias sed ipsum modi quaerat vitae eum odit harum perspiciatis commodi, quos dignissimos facilis tempore, deleniti, ab earum pariatur corrupti quis iure similique laboriosam obcaecati esse architecto illum voluptatum? Vero ab nostrum nemo voluptates commodi laborum placeat amet numquam error molestiae, odit, officiis ad quasi animi quibusdam incidunt? Excepturi iusto fuga vel! Quidem dolores neque, quod aut inventore in facilis harum laboriosam.</p>
</section>